
// Objective-C API for talking to the following Go packages
//
//	wallet_sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wallet_sdk_FRAMEWORK_H__
#define __Wallet_sdk_FRAMEWORK_H__

#include "Wallet_sdk.objc.h"
#include "Universe.objc.h"

#endif
