// Objective-C API for talking to wallet_sdk Go package.
//   gobind -lang=objc wallet_sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Wallet_sdk_H__
#define __Wallet_sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Wallet_sdkAccountInfo;
@class Wallet_sdkAccountInfoResp;
@class Wallet_sdkCommonResp;
@class Wallet_sdkContractInfo;
@class Wallet_sdkContractInfoResp;
@class Wallet_sdkResponse;
@class Wallet_sdkTransactionInfo;
@class Wallet_sdkTransactionInfoResp;
@class Wallet_sdkTransferResp;
@protocol Wallet_sdkNodeService;
@class Wallet_sdkNodeService;

@protocol Wallet_sdkNodeService <NSObject>
// skipped method NodeService.BuildContractInfo with unsupported parameter or return types

// skipped method NodeService.BuildTransferInfo with unsupported parameter or return types

// skipped method NodeService.ChainID with unsupported parameter or return types

- (void)close;
// skipped method NodeService.GetBalance with unsupported parameter or return types

// skipped method NodeService.GetBalanceByContract with unsupported parameter or return types

- (BOOL)getBlockHeight:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.GetDecimals with unsupported parameter or return types

// skipped method NodeService.GetNonce with unsupported parameter or return types

- (NSString* _Nonnull)getSymbol:(NSString* _Nullable)contractAddr error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.GetTransactionByHash with unsupported parameter or return types

- (NSString* _Nonnull)sendRawTransaction:(NSString* _Nullable)hexTx error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.SignAndSendTransfer with unsupported parameter or return types

// skipped method NodeService.SuggestGasPrice with unsupported parameter or return types

@end

/**
 * 账户信息
 */
@interface Wallet_sdkAccountInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull privateKey;
@property (nonatomic) NSString* _Nonnull publicKey;
@end

/**
 * 使用助记词生成账户信息
 */
@interface Wallet_sdkAccountInfoResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field AccountInfoResp.Status with unsupported type: wallet_sdk.Response

@property (nonatomic) Wallet_sdkAccountInfo* _Nullable data;
@end

/**
 * 使用通用返回结果
 */
@interface Wallet_sdkCommonResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field CommonResp.Status with unsupported type: wallet_sdk.Response

@property (nonatomic) NSString* _Nonnull data;
@end

/**
 * 合约信息
 */
@interface Wallet_sdkContractInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull symbol;
@property (nonatomic) NSString* _Nonnull decimals;
@end

/**
 * 查询合约信息
 */
@interface Wallet_sdkContractInfoResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ContractInfoResp.Status with unsupported type: wallet_sdk.Response

@property (nonatomic) Wallet_sdkContractInfo* _Nullable data;
@end

/**
 * 返回结构
 */
@interface Wallet_sdkResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t code;
@property (nonatomic) NSString* _Nonnull message;
@end

/**
 * 交易信息
 */
@interface Wallet_sdkTransactionInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TransactionInfo.TxInfo with unsupported type: interface{}

@property (nonatomic) BOOL isPending;
@end

/**
 * 查询交易信息
 */
@interface Wallet_sdkTransactionInfoResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TransactionInfoResp.Status with unsupported type: wallet_sdk.Response

@property (nonatomic) Wallet_sdkTransactionInfo* _Nullable data;
@end

/**
 * 构建交易信息
 */
@interface Wallet_sdkTransferResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TransferResp.Status with unsupported type: wallet_sdk.Response

// skipped field TransferResp.Data with unsupported type: interface{}

@end

/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkBSC_Testnet;
/**
 * contract abi params
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkContractDecimals;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkContractSymbol;
/**
 * ETH系网络
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkETH_Rinkeby;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkETH_Sepolia;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkHT_Testnet;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkMainCoinBSC;
/**
 * chain Symbol
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkMainCoinEth;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkPOLYGON_Testnet;
/**
 * 常用参数
 */
FOUNDATION_EXPORT const int64_t Wallet_sdkRES_CODE_FAILED;
/**
 * 返回结果参数
 */
FOUNDATION_EXPORT const int64_t Wallet_sdkRES_CODE_SUCCESS;
/**
 * jsonRpc state
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkStateEarliest;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkStateLatest;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkStatePending;
/**
 * 常用参数
 */
FOUNDATION_EXPORT NSString* _Nonnull const Wallet_sdkTRX_Nile;

@interface Wallet_sdk : NSObject
// skipped variable BSCTestnet with unsupported type: wallet_sdk/client.Node

// skipped variable ETHRinkeby with unsupported type: wallet_sdk/client.Node

// skipped variable ETHSepolia with unsupported type: wallet_sdk/client.Node

// skipped variable GasAverage with unsupported type: github.com/shopspring/decimal.Decimal

// skipped variable GasFast with unsupported type: github.com/shopspring/decimal.Decimal

// skipped variable GasHigh with unsupported type: github.com/shopspring/decimal.Decimal

// skipped variable HTTestnet with unsupported type: wallet_sdk/client.Node

// skipped variable POLYGONTestnet with unsupported type: wallet_sdk/client.Node

// skipped variable ResFailed with unsupported type: wallet_sdk.Response

// skipped variable ResSuccess with unsupported type: wallet_sdk.Response

// skipped variable TRXTestnet with unsupported type: wallet_sdk/client.Node

@end

// skipped function BuildContractInfo with unsupported parameter or return types


/**
 * *
 * 构建交易
 *
 * Params (chainName, to, contract, amount, gasPrice, nonce string)
 * chainName:
 *   链名称
 * to:
 *   目标地址
 * contract:
 *   合约地址 发送代币的合约地址
 * amount:
 *   发送金额
 * gasPrice:
 *   gas price 单位：Gwei
 * nonce:
 *   发送账户的nonce
 */
FOUNDATION_EXPORT Wallet_sdkTransferResp* _Nullable Wallet_sdkBuildTransferInfo(NSString* _Nullable chainName, NSString* _Nullable fromAddr, NSString* _Nullable toAddr, NSString* _Nullable amount, NSString* _Nullable contract, NSString* _Nullable gasPrice, NSString* _Nullable nonce);

FOUNDATION_EXPORT Wallet_sdkAccountInfoResp* _Nullable Wallet_sdkGenerateAccountByMnemonic(NSString* _Nullable mnemonic, NSString* _Nullable symbol);

FOUNDATION_EXPORT Wallet_sdkCommonResp* _Nullable Wallet_sdkGenerateMnemonic(long length, NSString* _Nullable langauge);

/**
 * *
 * 查询地址主币余额
 *
 * Params (chainName, address string)
 * chainName:
 *   链名称
 * address:
 *   查询地址
 */
FOUNDATION_EXPORT Wallet_sdkCommonResp* _Nullable Wallet_sdkGetBalanceByAddress(NSString* _Nullable chainName, NSString* _Nullable address);

/**
 * *
 * 查询地址代币合约余额
 *
 * Params (chainName, address, contract string)
 * chainName:
 *   链名称
 * address:
 *   查询地址
 * contract:
 *   合约地址
 */
FOUNDATION_EXPORT Wallet_sdkCommonResp* _Nullable Wallet_sdkGetBalanceByAddressAndContract(NSString* _Nullable chainName, NSString* _Nullable address, NSString* _Nullable contract);

/**
 * *
 * 查询最新块高
 *
 * Params (chainName)
 * chainName:
 *   链名称
 */
FOUNDATION_EXPORT Wallet_sdkCommonResp* _Nullable Wallet_sdkGetBlockHeight(NSString* _Nullable chainName);

/**
 * *
 * 查询合约信息
 *
 * Params (chainName, contract string)
 * chainName:
 *   链名称
 * contract:
 *   合约地址
 */
FOUNDATION_EXPORT Wallet_sdkContractInfoResp* _Nullable Wallet_sdkGetContractInfo(NSString* _Nullable chainName, NSString* _Nullable contract);

/**
 * *
 * 请求建议GasPrice
 *
 * Params (chainName string)
 * chainName:
 *   链名称
 */
FOUNDATION_EXPORT Wallet_sdkTransferResp* _Nullable Wallet_sdkGetGasPrice(NSString* _Nullable chainName);

/**
 * *
 * 请求nonce值
 *
 * Params (chainName, address, params string)
 * chainName:
 *   链名称
 * address:
 *   查询地址
 * params:
 *   参数："latest"、"earliest"或"pending"
 */
FOUNDATION_EXPORT Wallet_sdkCommonResp* _Nullable Wallet_sdkGetNonce(NSString* _Nullable chainName, NSString* _Nullable address, NSString* _Nullable params);

/**
 * *
 * 查询交易信息
 *
 * Params (chainName, txHash string)
 * chainName:
 *   链名称
 * txHash:
 *   交易hash
 */
FOUNDATION_EXPORT Wallet_sdkTransactionInfoResp* _Nullable Wallet_sdkGetTransaction(NSString* _Nullable chainName, NSString* _Nullable txHash);

FOUNDATION_EXPORT id<Wallet_sdkNodeService> _Nullable Wallet_sdkNewNodeService(NSString* _Nullable chainName, NSError* _Nullable* _Nullable error);

/**
 * *
 * 签名并广播交易
 *
 * Params (chainName, priKey string, apiTx interface{})
 * chainName:
 *   链名称
 * priKey:
 *   私钥
 * apiTx:
 *   交易信息
 */
FOUNDATION_EXPORT Wallet_sdkTransferResp* _Nullable Wallet_sdkSignAndSendTransferInfo(NSString* _Nullable chainName, NSString* _Nullable priKey, NSString* _Nullable apiTx);

@class Wallet_sdkNodeService;

@interface Wallet_sdkNodeService : NSObject <goSeqRefInterface, Wallet_sdkNodeService> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped method NodeService.BuildContractInfo with unsupported parameter or return types

// skipped method NodeService.BuildTransferInfo with unsupported parameter or return types

// skipped method NodeService.ChainID with unsupported parameter or return types

- (void)close;
// skipped method NodeService.GetBalance with unsupported parameter or return types

// skipped method NodeService.GetBalanceByContract with unsupported parameter or return types

- (BOOL)getBlockHeight:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.GetDecimals with unsupported parameter or return types

// skipped method NodeService.GetNonce with unsupported parameter or return types

- (NSString* _Nonnull)getSymbol:(NSString* _Nullable)contractAddr error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.GetTransactionByHash with unsupported parameter or return types

- (NSString* _Nonnull)sendRawTransaction:(NSString* _Nullable)hexTx error:(NSError* _Nullable* _Nullable)error;
// skipped method NodeService.SignAndSendTransfer with unsupported parameter or return types

// skipped method NodeService.SuggestGasPrice with unsupported parameter or return types

@end

#endif
